name: corks_cedar
description: An embedded authorization token format, based off Google's macaroons.
version: 1.0.0
repository: https://github.com/celest-dev/corks/tree/main/dart

environment:
  sdk: ^3.8.0

dependencies:
  cedar: ^1.0.0
  collection: ^1.18.0
  convert: ^3.0.0
  crypto: ^3.0.0
  cryptography: ^2.7.0
  args: ^2.5.0
  fixnum: ^1.1.0
  meta: ^1.10.0
  protobuf: ^5.0.0

executables:
  corks: corks

dev_dependencies:
  benchmark_harness: ^2.3.1
  build_runner: ^2.10.1
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1
  lints: ^6.0.0
  test: ^1.24.0
