name: corks_cedar
description: An embedded authorization token format, based off Google's macaroons.
version: 0.1.2
repository: https://github.com/celest-dev/corks/tree/main/dart

environment:
  sdk: ^3.3.0

dependencies:
  cedar: ^0.1.1
  crypto: ^3.0.3
  fixnum: ^1.1.0
  meta: ^1.10.0
  protobuf: ^3.1.0

dev_dependencies:
  lints: ">=3.0.0 <5.0.0"
  test: ^1.24.0
