name: corks_cedar
description: An embedded authorization token format, based off Google's macaroons.
version: 0.2.2
repository: https://github.com/celest-dev/corks/tree/main/dart

environment:
  sdk: ^3.3.0

dependencies:
  cedar: ^0.2.1
  collection: ^1.18.0
  convert: ^3.0.0
  crypto: ^3.0.0
  fixnum: ^1.1.0
  meta: ^1.10.0
  protobuf: ^3.1.0

dev_dependencies:
  lints: ">=4.0.0 <6.0.0"
  test: ^1.24.0
