name: corks_cedar
description: An embedded authorization token format, based off Google's macaroons.
version: 0.2.4
repository: https://github.com/celest-dev/corks/tree/main/dart

environment:
  sdk: ^3.7.0

dependencies:
  cedar: ^0.2.6
  collection: ^1.18.0
  convert: ^3.0.0
  crypto: ^3.0.0
  cryptography: ^2.7.0
  fixnum: ^1.1.0
  meta: ^1.10.0
  protobuf: ^4.0.0

dependency_overrides:
  cedar:
    path: ../../cedar/packages/cedar

dev_dependencies:
  build_runner: ^2.10.1
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1
  lints: ^6.0.0
  test: ^1.24.0
