// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: cedar/v4/context.proto

package cedarv4

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]*Value      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_cedar_v4_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v4_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_cedar_v4_context_proto_rawDescGZIP(), []int{0}
}

func (x *Context) GetValues() map[string]*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_cedar_v4_context_proto protoreflect.FileDescriptor

const file_cedar_v4_context_proto_rawDesc = "" +
	"\n" +
	"\x16cedar/v4/context.proto\x12\bcedar.v4\x1a\x14cedar/v4/value.proto\"\x8c\x01\n" +
	"\aContext\x125\n" +
	"\x06values\x18\x01 \x03(\v2\x1d.cedar.v4.Context.ValuesEntryR\x06values\x1aJ\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.cedar.v4.ValueR\x05value:\x028\x01B\x94\x01\n" +
	"\fcom.cedar.v4B\fContextProtoP\x01Z5github.com/celest-dev/corks/go/proto/cedar/v4;cedarv4\xa2\x02\x03CXX\xaa\x02\bCedar.V4\xca\x02\bCedar\\V4\xe2\x02\x14Cedar\\V4\\GPBMetadata\xea\x02\tCedar::V4b\x06proto3"

var (
	file_cedar_v4_context_proto_rawDescOnce sync.Once
	file_cedar_v4_context_proto_rawDescData []byte
)

func file_cedar_v4_context_proto_rawDescGZIP() []byte {
	file_cedar_v4_context_proto_rawDescOnce.Do(func() {
		file_cedar_v4_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cedar_v4_context_proto_rawDesc), len(file_cedar_v4_context_proto_rawDesc)))
	})
	return file_cedar_v4_context_proto_rawDescData
}

var file_cedar_v4_context_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cedar_v4_context_proto_goTypes = []any{
	(*Context)(nil), // 0: cedar.v4.Context
	nil,             // 1: cedar.v4.Context.ValuesEntry
	(*Value)(nil),   // 2: cedar.v4.Value
}
var file_cedar_v4_context_proto_depIdxs = []int32{
	1, // 0: cedar.v4.Context.values:type_name -> cedar.v4.Context.ValuesEntry
	2, // 1: cedar.v4.Context.ValuesEntry.value:type_name -> cedar.v4.Value
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cedar_v4_context_proto_init() }
func file_cedar_v4_context_proto_init() {
	if File_cedar_v4_context_proto != nil {
		return
	}
	file_cedar_v4_value_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cedar_v4_context_proto_rawDesc), len(file_cedar_v4_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cedar_v4_context_proto_goTypes,
		DependencyIndexes: file_cedar_v4_context_proto_depIdxs,
		MessageInfos:      file_cedar_v4_context_proto_msgTypes,
	}.Build()
	File_cedar_v4_context_proto = out.File
	file_cedar_v4_context_proto_goTypes = nil
	file_cedar_v4_context_proto_depIdxs = nil
}
