// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: cedar/v4/entity.proto

package cedarv4

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           *EntityUid             `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Parents       []*EntityUid           `protobuf:"bytes,2,rep,name=parents,proto3" json:"parents,omitempty"`
	Attributes    map[string]*Value      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags          map[string]*Value      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_cedar_v4_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v4_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_cedar_v4_entity_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetUid() *EntityUid {
	if x != nil {
		return x.Uid
	}
	return nil
}

func (x *Entity) GetParents() []*EntityUid {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *Entity) GetAttributes() map[string]*Value {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Entity) GetTags() map[string]*Value {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_cedar_v4_entity_proto protoreflect.FileDescriptor

const file_cedar_v4_entity_proto_rawDesc = "" +
	"\n" +
	"\x15cedar/v4/entity.proto\x12\bcedar.v4\x1a\x19cedar/v4/entity_uid.proto\x1a\x14cedar/v4/value.proto\"\xea\x02\n" +
	"\x06Entity\x12%\n" +
	"\x03uid\x18\x01 \x01(\v2\x13.cedar.v4.EntityUidR\x03uid\x12-\n" +
	"\aparents\x18\x02 \x03(\v2\x13.cedar.v4.EntityUidR\aparents\x12@\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2 .cedar.v4.Entity.AttributesEntryR\n" +
	"attributes\x12.\n" +
	"\x04tags\x18\x04 \x03(\v2\x1a.cedar.v4.Entity.TagsEntryR\x04tags\x1aN\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.cedar.v4.ValueR\x05value:\x028\x01\x1aH\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.cedar.v4.ValueR\x05value:\x028\x01B\x93\x01\n" +
	"\fcom.cedar.v4B\vEntityProtoP\x01Z5github.com/celest-dev/corks/go/proto/cedar/v4;cedarv4\xa2\x02\x03CXX\xaa\x02\bCedar.V4\xca\x02\bCedar\\V4\xe2\x02\x14Cedar\\V4\\GPBMetadata\xea\x02\tCedar::V4b\x06proto3"

var (
	file_cedar_v4_entity_proto_rawDescOnce sync.Once
	file_cedar_v4_entity_proto_rawDescData []byte
)

func file_cedar_v4_entity_proto_rawDescGZIP() []byte {
	file_cedar_v4_entity_proto_rawDescOnce.Do(func() {
		file_cedar_v4_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cedar_v4_entity_proto_rawDesc), len(file_cedar_v4_entity_proto_rawDesc)))
	})
	return file_cedar_v4_entity_proto_rawDescData
}

var file_cedar_v4_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cedar_v4_entity_proto_goTypes = []any{
	(*Entity)(nil),    // 0: cedar.v4.Entity
	nil,               // 1: cedar.v4.Entity.AttributesEntry
	nil,               // 2: cedar.v4.Entity.TagsEntry
	(*EntityUid)(nil), // 3: cedar.v4.EntityUid
	(*Value)(nil),     // 4: cedar.v4.Value
}
var file_cedar_v4_entity_proto_depIdxs = []int32{
	3, // 0: cedar.v4.Entity.uid:type_name -> cedar.v4.EntityUid
	3, // 1: cedar.v4.Entity.parents:type_name -> cedar.v4.EntityUid
	1, // 2: cedar.v4.Entity.attributes:type_name -> cedar.v4.Entity.AttributesEntry
	2, // 3: cedar.v4.Entity.tags:type_name -> cedar.v4.Entity.TagsEntry
	4, // 4: cedar.v4.Entity.AttributesEntry.value:type_name -> cedar.v4.Value
	4, // 5: cedar.v4.Entity.TagsEntry.value:type_name -> cedar.v4.Value
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_cedar_v4_entity_proto_init() }
func file_cedar_v4_entity_proto_init() {
	if File_cedar_v4_entity_proto != nil {
		return
	}
	file_cedar_v4_entity_uid_proto_init()
	file_cedar_v4_value_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cedar_v4_entity_proto_rawDesc), len(file_cedar_v4_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cedar_v4_entity_proto_goTypes,
		DependencyIndexes: file_cedar_v4_entity_proto_depIdxs,
		MessageInfos:      file_cedar_v4_entity_proto_msgTypes,
	}.Build()
	File_cedar_v4_entity_proto = out.File
	file_cedar_v4_entity_proto_goTypes = nil
	file_cedar_v4_entity_proto_depIdxs = nil
}
