// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: cedar/v4/value.proto

package cedarv4

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_String_
	//	*Value_Long
	//	*Value_Bool
	//	*Value_Set
	//	*Value_Record
	//	*Value_ExtensionCall
	//	*Value_Entity
	//	*Value_Decimal
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_cedar_v4_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v4_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_cedar_v4_value_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetString_() *wrapperspb.StringValue {
	if x != nil {
		if x, ok := x.Value.(*Value_String_); ok {
			return x.String_
		}
	}
	return nil
}

func (x *Value) GetLong() *wrapperspb.Int64Value {
	if x != nil {
		if x, ok := x.Value.(*Value_Long); ok {
			return x.Long
		}
	}
	return nil
}

func (x *Value) GetBool() *wrapperspb.BoolValue {
	if x != nil {
		if x, ok := x.Value.(*Value_Bool); ok {
			return x.Bool
		}
	}
	return nil
}

func (x *Value) GetSet() *SetValue {
	if x != nil {
		if x, ok := x.Value.(*Value_Set); ok {
			return x.Set
		}
	}
	return nil
}

func (x *Value) GetRecord() *RecordValue {
	if x != nil {
		if x, ok := x.Value.(*Value_Record); ok {
			return x.Record
		}
	}
	return nil
}

func (x *Value) GetExtensionCall() *ExtensionCall {
	if x != nil {
		if x, ok := x.Value.(*Value_ExtensionCall); ok {
			return x.ExtensionCall
		}
	}
	return nil
}

func (x *Value) GetEntity() *EntityValue {
	if x != nil {
		if x, ok := x.Value.(*Value_Entity); ok {
			return x.Entity
		}
	}
	return nil
}

func (x *Value) GetDecimal() *DecimalValue {
	if x != nil {
		if x, ok := x.Value.(*Value_Decimal); ok {
			return x.Decimal
		}
	}
	return nil
}

type isValue_Value interface {
	isValue_Value()
}

type Value_String_ struct {
	String_ *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=string,proto3,oneof"`
}

type Value_Long struct {
	Long *wrapperspb.Int64Value `protobuf:"bytes,2,opt,name=long,proto3,oneof"`
}

type Value_Bool struct {
	Bool *wrapperspb.BoolValue `protobuf:"bytes,3,opt,name=bool,proto3,oneof"`
}

type Value_Set struct {
	Set *SetValue `protobuf:"bytes,4,opt,name=set,proto3,oneof"`
}

type Value_Record struct {
	Record *RecordValue `protobuf:"bytes,5,opt,name=record,proto3,oneof"`
}

type Value_ExtensionCall struct {
	ExtensionCall *ExtensionCall `protobuf:"bytes,6,opt,name=extension_call,json=extensionCall,proto3,oneof"`
}

type Value_Entity struct {
	Entity *EntityValue `protobuf:"bytes,7,opt,name=entity,proto3,oneof"`
}

type Value_Decimal struct {
	Decimal *DecimalValue `protobuf:"bytes,8,opt,name=decimal,proto3,oneof"`
}

func (*Value_String_) isValue_Value() {}

func (*Value_Long) isValue_Value() {}

func (*Value_Bool) isValue_Value() {}

func (*Value_Set) isValue_Value() {}

func (*Value_Record) isValue_Value() {}

func (*Value_ExtensionCall) isValue_Value() {}

func (*Value_Entity) isValue_Value() {}

func (*Value_Decimal) isValue_Value() {}

type SetValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*Value               `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValue) Reset() {
	*x = SetValue{}
	mi := &file_cedar_v4_value_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValue) ProtoMessage() {}

func (x *SetValue) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v4_value_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValue.ProtoReflect.Descriptor instead.
func (*SetValue) Descriptor() ([]byte, []int) {
	return file_cedar_v4_value_proto_rawDescGZIP(), []int{1}
}

func (x *SetValue) GetElements() []*Value {
	if x != nil {
		return x.Elements
	}
	return nil
}

type RecordValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    map[string]*Value      `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordValue) Reset() {
	*x = RecordValue{}
	mi := &file_cedar_v4_value_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordValue) ProtoMessage() {}

func (x *RecordValue) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v4_value_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordValue.ProtoReflect.Descriptor instead.
func (*RecordValue) Descriptor() ([]byte, []int) {
	return file_cedar_v4_value_proto_rawDescGZIP(), []int{2}
}

func (x *RecordValue) GetAttributes() map[string]*Value {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ExtensionCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fn            string                 `protobuf:"bytes,1,opt,name=fn,proto3" json:"fn,omitempty"`
	Arg           *Value                 `protobuf:"bytes,2,opt,name=arg,proto3" json:"arg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionCall) Reset() {
	*x = ExtensionCall{}
	mi := &file_cedar_v4_value_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionCall) ProtoMessage() {}

func (x *ExtensionCall) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v4_value_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionCall.ProtoReflect.Descriptor instead.
func (*ExtensionCall) Descriptor() ([]byte, []int) {
	return file_cedar_v4_value_proto_rawDescGZIP(), []int{3}
}

func (x *ExtensionCall) GetFn() string {
	if x != nil {
		return x.Fn
	}
	return ""
}

func (x *ExtensionCall) GetArg() *Value {
	if x != nil {
		return x.Arg
	}
	return nil
}

type EntityValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           *EntityUid             `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityValue) Reset() {
	*x = EntityValue{}
	mi := &file_cedar_v4_value_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityValue) ProtoMessage() {}

func (x *EntityValue) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v4_value_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityValue.ProtoReflect.Descriptor instead.
func (*EntityValue) Descriptor() ([]byte, []int) {
	return file_cedar_v4_value_proto_rawDescGZIP(), []int{4}
}

func (x *EntityValue) GetUid() *EntityUid {
	if x != nil {
		return x.Uid
	}
	return nil
}

type DecimalValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecimalValue) Reset() {
	*x = DecimalValue{}
	mi := &file_cedar_v4_value_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecimalValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecimalValue) ProtoMessage() {}

func (x *DecimalValue) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v4_value_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecimalValue.ProtoReflect.Descriptor instead.
func (*DecimalValue) Descriptor() ([]byte, []int) {
	return file_cedar_v4_value_proto_rawDescGZIP(), []int{5}
}

func (x *DecimalValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_cedar_v4_value_proto protoreflect.FileDescriptor

const file_cedar_v4_value_proto_rawDesc = "" +
	"\n" +
	"\x14cedar/v4/value.proto\x12\bcedar.v4\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x19cedar/v4/entity_uid.proto\"\xad\x03\n" +
	"\x05Value\x126\n" +
	"\x06string\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueH\x00R\x06string\x121\n" +
	"\x04long\x18\x02 \x01(\v2\x1b.google.protobuf.Int64ValueH\x00R\x04long\x120\n" +
	"\x04bool\x18\x03 \x01(\v2\x1a.google.protobuf.BoolValueH\x00R\x04bool\x12&\n" +
	"\x03set\x18\x04 \x01(\v2\x12.cedar.v4.SetValueH\x00R\x03set\x12/\n" +
	"\x06record\x18\x05 \x01(\v2\x15.cedar.v4.RecordValueH\x00R\x06record\x12@\n" +
	"\x0eextension_call\x18\x06 \x01(\v2\x17.cedar.v4.ExtensionCallH\x00R\rextensionCall\x12/\n" +
	"\x06entity\x18\a \x01(\v2\x15.cedar.v4.EntityValueH\x00R\x06entity\x122\n" +
	"\adecimal\x18\b \x01(\v2\x16.cedar.v4.DecimalValueH\x00R\adecimalB\a\n" +
	"\x05value\"7\n" +
	"\bSetValue\x12+\n" +
	"\belements\x18\x01 \x03(\v2\x0f.cedar.v4.ValueR\belements\"\xa4\x01\n" +
	"\vRecordValue\x12E\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2%.cedar.v4.RecordValue.AttributesEntryR\n" +
	"attributes\x1aN\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.cedar.v4.ValueR\x05value:\x028\x01\"B\n" +
	"\rExtensionCall\x12\x0e\n" +
	"\x02fn\x18\x01 \x01(\tR\x02fn\x12!\n" +
	"\x03arg\x18\x02 \x01(\v2\x0f.cedar.v4.ValueR\x03arg\"4\n" +
	"\vEntityValue\x12%\n" +
	"\x03uid\x18\x01 \x01(\v2\x13.cedar.v4.EntityUidR\x03uid\"$\n" +
	"\fDecimalValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueB\x92\x01\n" +
	"\fcom.cedar.v4B\n" +
	"ValueProtoP\x01Z5github.com/celest-dev/corks/go/proto/cedar/v4;cedarv4\xa2\x02\x03CXX\xaa\x02\bCedar.V4\xca\x02\bCedar\\V4\xe2\x02\x14Cedar\\V4\\GPBMetadata\xea\x02\tCedar::V4b\x06proto3"

var (
	file_cedar_v4_value_proto_rawDescOnce sync.Once
	file_cedar_v4_value_proto_rawDescData []byte
)

func file_cedar_v4_value_proto_rawDescGZIP() []byte {
	file_cedar_v4_value_proto_rawDescOnce.Do(func() {
		file_cedar_v4_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cedar_v4_value_proto_rawDesc), len(file_cedar_v4_value_proto_rawDesc)))
	})
	return file_cedar_v4_value_proto_rawDescData
}

var file_cedar_v4_value_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cedar_v4_value_proto_goTypes = []any{
	(*Value)(nil),                  // 0: cedar.v4.Value
	(*SetValue)(nil),               // 1: cedar.v4.SetValue
	(*RecordValue)(nil),            // 2: cedar.v4.RecordValue
	(*ExtensionCall)(nil),          // 3: cedar.v4.ExtensionCall
	(*EntityValue)(nil),            // 4: cedar.v4.EntityValue
	(*DecimalValue)(nil),           // 5: cedar.v4.DecimalValue
	nil,                            // 6: cedar.v4.RecordValue.AttributesEntry
	(*wrapperspb.StringValue)(nil), // 7: google.protobuf.StringValue
	(*wrapperspb.Int64Value)(nil),  // 8: google.protobuf.Int64Value
	(*wrapperspb.BoolValue)(nil),   // 9: google.protobuf.BoolValue
	(*EntityUid)(nil),              // 10: cedar.v4.EntityUid
}
var file_cedar_v4_value_proto_depIdxs = []int32{
	7,  // 0: cedar.v4.Value.string:type_name -> google.protobuf.StringValue
	8,  // 1: cedar.v4.Value.long:type_name -> google.protobuf.Int64Value
	9,  // 2: cedar.v4.Value.bool:type_name -> google.protobuf.BoolValue
	1,  // 3: cedar.v4.Value.set:type_name -> cedar.v4.SetValue
	2,  // 4: cedar.v4.Value.record:type_name -> cedar.v4.RecordValue
	3,  // 5: cedar.v4.Value.extension_call:type_name -> cedar.v4.ExtensionCall
	4,  // 6: cedar.v4.Value.entity:type_name -> cedar.v4.EntityValue
	5,  // 7: cedar.v4.Value.decimal:type_name -> cedar.v4.DecimalValue
	0,  // 8: cedar.v4.SetValue.elements:type_name -> cedar.v4.Value
	6,  // 9: cedar.v4.RecordValue.attributes:type_name -> cedar.v4.RecordValue.AttributesEntry
	0,  // 10: cedar.v4.ExtensionCall.arg:type_name -> cedar.v4.Value
	10, // 11: cedar.v4.EntityValue.uid:type_name -> cedar.v4.EntityUid
	0,  // 12: cedar.v4.RecordValue.AttributesEntry.value:type_name -> cedar.v4.Value
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_cedar_v4_value_proto_init() }
func file_cedar_v4_value_proto_init() {
	if File_cedar_v4_value_proto != nil {
		return
	}
	file_cedar_v4_entity_uid_proto_init()
	file_cedar_v4_value_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_String_)(nil),
		(*Value_Long)(nil),
		(*Value_Bool)(nil),
		(*Value_Set)(nil),
		(*Value_Record)(nil),
		(*Value_ExtensionCall)(nil),
		(*Value_Entity)(nil),
		(*Value_Decimal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cedar_v4_value_proto_rawDesc), len(file_cedar_v4_value_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cedar_v4_value_proto_goTypes,
		DependencyIndexes: file_cedar_v4_value_proto_depIdxs,
		MessageInfos:      file_cedar_v4_value_proto_msgTypes,
	}.Build()
	File_cedar_v4_value_proto = out.File
	file_cedar_v4_value_proto_goTypes = nil
	file_cedar_v4_value_proto_depIdxs = nil
}
