// Experimental options controlling Dart code generation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: dart_options/dart_options.proto

package dart_options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	_ "google.golang.org/protobuf/types/pluginpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A mixin that can be used in the 'with' clause of the generated Dart class
// for a proto message.
type DartMixin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the mixin class.
	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// A URI pointing to the Dart library that defines the mixin.
	// The generated Dart code will use this in an import statement.
	ImportFrom *string `protobuf:"bytes,2,opt,name=import_from,json=importFrom" json:"import_from,omitempty"`
	// The name of another mixin to be applied ahead of this one.
	// The generated class for the message will inherit from all mixins
	// in the parent chain.
	Parent        *string `protobuf:"bytes,3,opt,name=parent" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DartMixin) Reset() {
	*x = DartMixin{}
	mi := &file_dart_options_dart_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DartMixin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DartMixin) ProtoMessage() {}

func (x *DartMixin) ProtoReflect() protoreflect.Message {
	mi := &file_dart_options_dart_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DartMixin.ProtoReflect.Descriptor instead.
func (*DartMixin) Descriptor() ([]byte, []int) {
	return file_dart_options_dart_options_proto_rawDescGZIP(), []int{0}
}

func (x *DartMixin) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *DartMixin) GetImportFrom() string {
	if x != nil && x.ImportFrom != nil {
		return *x.ImportFrom
	}
	return ""
}

func (x *DartMixin) GetParent() string {
	if x != nil && x.Parent != nil {
		return *x.Parent
	}
	return ""
}

// Defines additional Dart imports to be used with messages in this file.
type Imports struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mixins to be used on messages in this file.
	// These mixins are in addition to internally defined mixins (e.g PbMapMixin)
	// and may override them.
	//
	// Warning: mixins are experimental. The protoc Dart plugin doesn't check
	// for name conflicts between mixin class members and generated class members,
	// so the generated code may contain errors. Therefore, running dartanalyzer
	// on the generated file is a good idea.
	Mixins        []*DartMixin `protobuf:"bytes,1,rep,name=mixins" json:"mixins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Imports) Reset() {
	*x = Imports{}
	mi := &file_dart_options_dart_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Imports) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Imports) ProtoMessage() {}

func (x *Imports) ProtoReflect() protoreflect.Message {
	mi := &file_dart_options_dart_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Imports.ProtoReflect.Descriptor instead.
func (*Imports) Descriptor() ([]byte, []int) {
	return file_dart_options_dart_options_proto_rawDescGZIP(), []int{1}
}

func (x *Imports) GetMixins() []*DartMixin {
	if x != nil {
		return x.Mixins
	}
	return nil
}

var file_dart_options_dart_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*Imports)(nil),
		Field:         28125061,
		Name:          "dart_options.imports",
		Tag:           "bytes,28125061,opt,name=imports",
		Filename:      "dart_options/dart_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         96128839,
		Name:          "dart_options.default_mixin",
		Tag:           "bytes,96128839,opt,name=default_mixin",
		Filename:      "dart_options/dart_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         96128839,
		Name:          "dart_options.mixin",
		Tag:           "bytes,96128839,opt,name=mixin",
		Filename:      "dart_options/dart_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         28205290,
		Name:          "dart_options.override_getter",
		Tag:           "varint,28205290,opt,name=override_getter",
		Filename:      "dart_options/dart_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         28937366,
		Name:          "dart_options.override_setter",
		Tag:           "varint,28937366,opt,name=override_setter",
		Filename:      "dart_options/dart_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         28937461,
		Name:          "dart_options.override_has_method",
		Tag:           "varint,28937461,opt,name=override_has_method",
		Filename:      "dart_options/dart_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         28907907,
		Name:          "dart_options.override_clear_method",
		Tag:           "varint,28907907,opt,name=override_clear_method",
		Filename:      "dart_options/dart_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         28700919,
		Name:          "dart_options.dart_name",
		Tag:           "bytes,28700919,opt,name=dart_name",
		Filename:      "dart_options/dart_options.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional dart_options.Imports imports = 28125061;
	E_Imports = &file_dart_options_dart_options_proto_extTypes[0]
	// Applies the named mixin to all messages in this file.
	// (May be overridden by the "mixin" option on a message.)
	// For now, "PbMapMixin" is the only available mixin.
	//
	// optional string default_mixin = 96128839;
	E_DefaultMixin = &file_dart_options_dart_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// Applies the named mixin.
	// For now, "PbMapMixin" is the only available mixin.
	// The empty string can be used to turn off mixins for this message.
	//
	// optional string mixin = 96128839;
	E_Mixin = &file_dart_options_dart_options_proto_extTypes[2]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// Adds @override annotation to the field's getter (for use with mixins).
	//
	// optional bool override_getter = 28205290;
	E_OverrideGetter = &file_dart_options_dart_options_proto_extTypes[3]
	// Adds @override annotation to the field's setter (for use with mixins).
	//
	// optional bool override_setter = 28937366;
	E_OverrideSetter = &file_dart_options_dart_options_proto_extTypes[4]
	// Adds @override annotation to the field's hasX() method (for use with
	// mixins).
	//
	// optional bool override_has_method = 28937461;
	E_OverrideHasMethod = &file_dart_options_dart_options_proto_extTypes[5]
	// Adds @override annotation to the field's clearX() method (for use with
	// mixins).
	//
	// optional bool override_clear_method = 28907907;
	E_OverrideClearMethod = &file_dart_options_dart_options_proto_extTypes[6]
	// Uses the given name for getters, setters and as suffixes for has/clear
	// methods in the generated Dart file. Should be lowerCamelCase.
	//
	// optional string dart_name = 28700919;
	E_DartName = &file_dart_options_dart_options_proto_extTypes[7]
)

var File_dart_options_dart_options_proto protoreflect.FileDescriptor

const file_dart_options_dart_options_proto_rawDesc = "" +
	"\n" +
	"\x1fdart_options/dart_options.proto\x12\fdart_options\x1a google/protobuf/descriptor.proto\x1a%google/protobuf/compiler/plugin.proto\"X\n" +
	"\tDartMixin\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vimport_from\x18\x02 \x01(\tR\n" +
	"importFrom\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\tR\x06parent\":\n" +
	"\aImports\x12/\n" +
	"\x06mixins\x18\x01 \x03(\v2\x17.dart_options.DartMixinR\x06mixins:P\n" +
	"\aimports\x12\x1c.google.protobuf.FileOptions\x18\x85ϴ\r \x01(\v2\x15.dart_options.ImportsR\aimports:D\n" +
	"\rdefault_mixin\x12\x1c.google.protobuf.FileOptions\x18Ǟ\xeb- \x01(\tR\fdefaultMixin:8\n" +
	"\x05mixin\x12\x1f.google.protobuf.MessageOptions\x18Ǟ\xeb- \x01(\tR\x05mixin:I\n" +
	"\x0foverride_getter\x12\x1d.google.protobuf.FieldOptions\x18\xea\xc1\xb9\r \x01(\bR\x0eoverrideGetter:I\n" +
	"\x0foverride_setter\x12\x1d.google.protobuf.FieldOptions\x18\x96\x99\xe6\r \x01(\bR\x0eoverrideSetter:P\n" +
	"\x13override_has_method\x12\x1d.google.protobuf.FieldOptions\x18\xf5\x99\xe6\r \x01(\bR\x11overrideHasMethod:T\n" +
	"\x15override_clear_method\x12\x1d.google.protobuf.FieldOptions\x18\x83\xb3\xe4\r \x01(\bR\x13overrideClearMethod:=\n" +
	"\tdart_name\x12\x1d.google.protobuf.FieldOptions\x18\xf7\xe1\xd7\r \x01(\tR\bdartNameB\xa3\x01\n" +
	"\x10com.dart_optionsB\x10DartOptionsProtoP\x01Z1github.com/celest-dev/corks/go/proto/dart_options\xa2\x02\x03DXX\xaa\x02\vDartOptions\xca\x02\vDartOptions\xe2\x02\x17DartOptions\\GPBMetadata\xea\x02\vDartOptions"

var (
	file_dart_options_dart_options_proto_rawDescOnce sync.Once
	file_dart_options_dart_options_proto_rawDescData []byte
)

func file_dart_options_dart_options_proto_rawDescGZIP() []byte {
	file_dart_options_dart_options_proto_rawDescOnce.Do(func() {
		file_dart_options_dart_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dart_options_dart_options_proto_rawDesc), len(file_dart_options_dart_options_proto_rawDesc)))
	})
	return file_dart_options_dart_options_proto_rawDescData
}

var file_dart_options_dart_options_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dart_options_dart_options_proto_goTypes = []any{
	(*DartMixin)(nil),                   // 0: dart_options.DartMixin
	(*Imports)(nil),                     // 1: dart_options.Imports
	(*descriptorpb.FileOptions)(nil),    // 2: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
}
var file_dart_options_dart_options_proto_depIdxs = []int32{
	0,  // 0: dart_options.Imports.mixins:type_name -> dart_options.DartMixin
	2,  // 1: dart_options.imports:extendee -> google.protobuf.FileOptions
	2,  // 2: dart_options.default_mixin:extendee -> google.protobuf.FileOptions
	3,  // 3: dart_options.mixin:extendee -> google.protobuf.MessageOptions
	4,  // 4: dart_options.override_getter:extendee -> google.protobuf.FieldOptions
	4,  // 5: dart_options.override_setter:extendee -> google.protobuf.FieldOptions
	4,  // 6: dart_options.override_has_method:extendee -> google.protobuf.FieldOptions
	4,  // 7: dart_options.override_clear_method:extendee -> google.protobuf.FieldOptions
	4,  // 8: dart_options.dart_name:extendee -> google.protobuf.FieldOptions
	1,  // 9: dart_options.imports:type_name -> dart_options.Imports
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	9,  // [9:10] is the sub-list for extension type_name
	1,  // [1:9] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_dart_options_dart_options_proto_init() }
func file_dart_options_dart_options_proto_init() {
	if File_dart_options_dart_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dart_options_dart_options_proto_rawDesc), len(file_dart_options_dart_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 8,
			NumServices:   0,
		},
		GoTypes:           file_dart_options_dart_options_proto_goTypes,
		DependencyIndexes: file_dart_options_dart_options_proto_depIdxs,
		MessageInfos:      file_dart_options_dart_options_proto_msgTypes,
		ExtensionInfos:    file_dart_options_dart_options_proto_extTypes,
	}.Build()
	File_dart_options_dart_options_proto = out.File
	file_dart_options_dart_options_proto_goTypes = nil
	file_dart_options_dart_options_proto_depIdxs = nil
}
