// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: cedar/v3/entity_uid.proto

package cedarv3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityUid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *EntityUid) Reset() {
	*x = EntityUid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cedar_v3_entity_uid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityUid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityUid) ProtoMessage() {}

func (x *EntityUid) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v3_entity_uid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityUid.ProtoReflect.Descriptor instead.
func (*EntityUid) Descriptor() ([]byte, []int) {
	return file_cedar_v3_entity_uid_proto_rawDescGZIP(), []int{0}
}

func (x *EntityUid) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EntityUid) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_cedar_v3_entity_uid_proto protoreflect.FileDescriptor

var file_cedar_v3_entity_uid_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2f, 0x76, 0x33, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x5f, 0x75, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x65, 0x64,
	0x61, 0x72, 0x2e, 0x76, 0x33, 0x22, 0x2f, 0x0a, 0x09, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x55,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x42, 0x96, 0x01, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x63,
	0x65, 0x64, 0x61, 0x72, 0x2e, 0x76, 0x33, 0x42, 0x0e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x55,
	0x69, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x65, 0x6c, 0x65, 0x73, 0x74, 0x2d, 0x64, 0x65, 0x76,
	0x2f, 0x63, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x63, 0x65, 0x64, 0x61, 0x72, 0x2f, 0x76, 0x33, 0x3b, 0x63, 0x65, 0x64, 0x61, 0x72, 0x76, 0x33,
	0xa2, 0x02, 0x03, 0x43, 0x58, 0x58, 0xaa, 0x02, 0x08, 0x43, 0x65, 0x64, 0x61, 0x72, 0x2e, 0x56,
	0x33, 0xca, 0x02, 0x08, 0x43, 0x65, 0x64, 0x61, 0x72, 0x5c, 0x56, 0x33, 0xe2, 0x02, 0x14, 0x43,
	0x65, 0x64, 0x61, 0x72, 0x5c, 0x56, 0x33, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x43, 0x65, 0x64, 0x61, 0x72, 0x3a, 0x3a, 0x56, 0x33, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cedar_v3_entity_uid_proto_rawDescOnce sync.Once
	file_cedar_v3_entity_uid_proto_rawDescData = file_cedar_v3_entity_uid_proto_rawDesc
)

func file_cedar_v3_entity_uid_proto_rawDescGZIP() []byte {
	file_cedar_v3_entity_uid_proto_rawDescOnce.Do(func() {
		file_cedar_v3_entity_uid_proto_rawDescData = protoimpl.X.CompressGZIP(file_cedar_v3_entity_uid_proto_rawDescData)
	})
	return file_cedar_v3_entity_uid_proto_rawDescData
}

var file_cedar_v3_entity_uid_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cedar_v3_entity_uid_proto_goTypes = []any{
	(*EntityUid)(nil), // 0: cedar.v3.EntityUid
}
var file_cedar_v3_entity_uid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cedar_v3_entity_uid_proto_init() }
func file_cedar_v3_entity_uid_proto_init() {
	if File_cedar_v3_entity_uid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cedar_v3_entity_uid_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EntityUid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cedar_v3_entity_uid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cedar_v3_entity_uid_proto_goTypes,
		DependencyIndexes: file_cedar_v3_entity_uid_proto_depIdxs,
		MessageInfos:      file_cedar_v3_entity_uid_proto_msgTypes,
	}.Build()
	File_cedar_v3_entity_uid_proto = out.File
	file_cedar_v3_entity_uid_proto_rawDesc = nil
	file_cedar_v3_entity_uid_proto_goTypes = nil
	file_cedar_v3_entity_uid_proto_depIdxs = nil
}
