// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: cedar/v3/value.proto

package cedarv3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*Value_String_
	//	*Value_Long
	//	*Value_Bool
	//	*Value_Set
	//	*Value_Record
	//	*Value_ExtensionCall
	//	*Value_Entity
	//	*Value_Decimal
	Value isValue_Value `protobuf_oneof:"value"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cedar_v3_value_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v3_value_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_cedar_v3_value_proto_rawDescGZIP(), []int{0}
}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Value) GetString_() *wrapperspb.StringValue {
	if x, ok := x.GetValue().(*Value_String_); ok {
		return x.String_
	}
	return nil
}

func (x *Value) GetLong() *wrapperspb.Int64Value {
	if x, ok := x.GetValue().(*Value_Long); ok {
		return x.Long
	}
	return nil
}

func (x *Value) GetBool() *wrapperspb.BoolValue {
	if x, ok := x.GetValue().(*Value_Bool); ok {
		return x.Bool
	}
	return nil
}

func (x *Value) GetSet() *SetValue {
	if x, ok := x.GetValue().(*Value_Set); ok {
		return x.Set
	}
	return nil
}

func (x *Value) GetRecord() *RecordValue {
	if x, ok := x.GetValue().(*Value_Record); ok {
		return x.Record
	}
	return nil
}

func (x *Value) GetExtensionCall() *ExtensionCall {
	if x, ok := x.GetValue().(*Value_ExtensionCall); ok {
		return x.ExtensionCall
	}
	return nil
}

func (x *Value) GetEntity() *EntityValue {
	if x, ok := x.GetValue().(*Value_Entity); ok {
		return x.Entity
	}
	return nil
}

func (x *Value) GetDecimal() *DecimalValue {
	if x, ok := x.GetValue().(*Value_Decimal); ok {
		return x.Decimal
	}
	return nil
}

type isValue_Value interface {
	isValue_Value()
}

type Value_String_ struct {
	String_ *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=string,proto3,oneof"`
}

type Value_Long struct {
	Long *wrapperspb.Int64Value `protobuf:"bytes,2,opt,name=long,proto3,oneof"`
}

type Value_Bool struct {
	Bool *wrapperspb.BoolValue `protobuf:"bytes,3,opt,name=bool,proto3,oneof"`
}

type Value_Set struct {
	Set *SetValue `protobuf:"bytes,4,opt,name=set,proto3,oneof"`
}

type Value_Record struct {
	Record *RecordValue `protobuf:"bytes,5,opt,name=record,proto3,oneof"`
}

type Value_ExtensionCall struct {
	ExtensionCall *ExtensionCall `protobuf:"bytes,6,opt,name=extension_call,json=extensionCall,proto3,oneof"`
}

type Value_Entity struct {
	Entity *EntityValue `protobuf:"bytes,7,opt,name=entity,proto3,oneof"`
}

type Value_Decimal struct {
	Decimal *DecimalValue `protobuf:"bytes,8,opt,name=decimal,proto3,oneof"`
}

func (*Value_String_) isValue_Value() {}

func (*Value_Long) isValue_Value() {}

func (*Value_Bool) isValue_Value() {}

func (*Value_Set) isValue_Value() {}

func (*Value_Record) isValue_Value() {}

func (*Value_ExtensionCall) isValue_Value() {}

func (*Value_Entity) isValue_Value() {}

func (*Value_Decimal) isValue_Value() {}

type SetValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Elements []*Value `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
}

func (x *SetValue) Reset() {
	*x = SetValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cedar_v3_value_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValue) ProtoMessage() {}

func (x *SetValue) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v3_value_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValue.ProtoReflect.Descriptor instead.
func (*SetValue) Descriptor() ([]byte, []int) {
	return file_cedar_v3_value_proto_rawDescGZIP(), []int{1}
}

func (x *SetValue) GetElements() []*Value {
	if x != nil {
		return x.Elements
	}
	return nil
}

type RecordValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attributes map[string]*Value `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *RecordValue) Reset() {
	*x = RecordValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cedar_v3_value_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordValue) ProtoMessage() {}

func (x *RecordValue) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v3_value_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordValue.ProtoReflect.Descriptor instead.
func (*RecordValue) Descriptor() ([]byte, []int) {
	return file_cedar_v3_value_proto_rawDescGZIP(), []int{2}
}

func (x *RecordValue) GetAttributes() map[string]*Value {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ExtensionCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fn  string `protobuf:"bytes,1,opt,name=fn,proto3" json:"fn,omitempty"`
	Arg *Value `protobuf:"bytes,2,opt,name=arg,proto3" json:"arg,omitempty"`
}

func (x *ExtensionCall) Reset() {
	*x = ExtensionCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cedar_v3_value_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtensionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionCall) ProtoMessage() {}

func (x *ExtensionCall) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v3_value_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionCall.ProtoReflect.Descriptor instead.
func (*ExtensionCall) Descriptor() ([]byte, []int) {
	return file_cedar_v3_value_proto_rawDescGZIP(), []int{3}
}

func (x *ExtensionCall) GetFn() string {
	if x != nil {
		return x.Fn
	}
	return ""
}

func (x *ExtensionCall) GetArg() *Value {
	if x != nil {
		return x.Arg
	}
	return nil
}

type EntityValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid *EntityUid `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *EntityValue) Reset() {
	*x = EntityValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cedar_v3_value_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityValue) ProtoMessage() {}

func (x *EntityValue) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v3_value_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityValue.ProtoReflect.Descriptor instead.
func (*EntityValue) Descriptor() ([]byte, []int) {
	return file_cedar_v3_value_proto_rawDescGZIP(), []int{4}
}

func (x *EntityValue) GetUid() *EntityUid {
	if x != nil {
		return x.Uid
	}
	return nil
}

type DecimalValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DecimalValue) Reset() {
	*x = DecimalValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cedar_v3_value_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecimalValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecimalValue) ProtoMessage() {}

func (x *DecimalValue) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v3_value_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecimalValue.ProtoReflect.Descriptor instead.
func (*DecimalValue) Descriptor() ([]byte, []int) {
	return file_cedar_v3_value_proto_rawDescGZIP(), []int{5}
}

func (x *DecimalValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_cedar_v3_value_proto protoreflect.FileDescriptor

var file_cedar_v3_value_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2f, 0x76, 0x33, 0x2f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2e, 0x76, 0x33,
	0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x19, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2f, 0x76, 0x33, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x5f, 0x75, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xad, 0x03, 0x0a, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x31, 0x0a,
	0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e,
	0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x6f, 0x6e, 0x67,
	0x12, 0x30, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6f,
	0x6f, 0x6c, 0x12, 0x26, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2e, 0x76, 0x33, 0x2e, 0x53, 0x65, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x03, 0x73, 0x65, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x65, 0x64,
	0x61, 0x72, 0x2e, 0x76, 0x33, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x40, 0x0a, 0x0e, 0x65,
	0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2e, 0x76, 0x33, 0x2e, 0x45,
	0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x48, 0x00, 0x52, 0x0d,
	0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x2f, 0x0a,
	0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x63, 0x65, 0x64, 0x61, 0x72, 0x2e, 0x76, 0x33, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x32,
	0x0a, 0x07, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2e, 0x76, 0x33, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x6d,
	0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x07, 0x64, 0x65, 0x63, 0x69, 0x6d,
	0x61, 0x6c, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x37, 0x0a, 0x08, 0x53,
	0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x65, 0x64, 0x61,
	0x72, 0x2e, 0x76, 0x33, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x22, 0xa4, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x65, 0x64, 0x61, 0x72,
	0x2e, 0x76, 0x33, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x1a, 0x4e, 0x0a, 0x0f, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2e, 0x76, 0x33, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x42, 0x0a, 0x0d, 0x45,
	0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x66, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x66, 0x6e, 0x12, 0x21, 0x0a, 0x03,
	0x61, 0x72, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x65, 0x64, 0x61,
	0x72, 0x2e, 0x76, 0x33, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x61, 0x72, 0x67, 0x22,
	0x34, 0x0a, 0x0b, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x25,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x65,
	0x64, 0x61, 0x72, 0x2e, 0x76, 0x33, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x55, 0x69, 0x64,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x24, 0x0a, 0x0c, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x92, 0x01, 0x0a, 0x0c,
	0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2e, 0x76, 0x33, 0x42, 0x0a, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x65, 0x6c, 0x65, 0x73, 0x74, 0x2d, 0x64, 0x65,
	0x76, 0x2f, 0x63, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2f, 0x76, 0x33, 0x3b, 0x63, 0x65, 0x64, 0x61, 0x72, 0x76,
	0x33, 0xa2, 0x02, 0x03, 0x43, 0x58, 0x58, 0xaa, 0x02, 0x08, 0x43, 0x65, 0x64, 0x61, 0x72, 0x2e,
	0x56, 0x33, 0xca, 0x02, 0x08, 0x43, 0x65, 0x64, 0x61, 0x72, 0x5c, 0x56, 0x33, 0xe2, 0x02, 0x14,
	0x43, 0x65, 0x64, 0x61, 0x72, 0x5c, 0x56, 0x33, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x43, 0x65, 0x64, 0x61, 0x72, 0x3a, 0x3a, 0x56, 0x33,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cedar_v3_value_proto_rawDescOnce sync.Once
	file_cedar_v3_value_proto_rawDescData = file_cedar_v3_value_proto_rawDesc
)

func file_cedar_v3_value_proto_rawDescGZIP() []byte {
	file_cedar_v3_value_proto_rawDescOnce.Do(func() {
		file_cedar_v3_value_proto_rawDescData = protoimpl.X.CompressGZIP(file_cedar_v3_value_proto_rawDescData)
	})
	return file_cedar_v3_value_proto_rawDescData
}

var file_cedar_v3_value_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cedar_v3_value_proto_goTypes = []any{
	(*Value)(nil),                  // 0: cedar.v3.Value
	(*SetValue)(nil),               // 1: cedar.v3.SetValue
	(*RecordValue)(nil),            // 2: cedar.v3.RecordValue
	(*ExtensionCall)(nil),          // 3: cedar.v3.ExtensionCall
	(*EntityValue)(nil),            // 4: cedar.v3.EntityValue
	(*DecimalValue)(nil),           // 5: cedar.v3.DecimalValue
	nil,                            // 6: cedar.v3.RecordValue.AttributesEntry
	(*wrapperspb.StringValue)(nil), // 7: google.protobuf.StringValue
	(*wrapperspb.Int64Value)(nil),  // 8: google.protobuf.Int64Value
	(*wrapperspb.BoolValue)(nil),   // 9: google.protobuf.BoolValue
	(*EntityUid)(nil),              // 10: cedar.v3.EntityUid
}
var file_cedar_v3_value_proto_depIdxs = []int32{
	7,  // 0: cedar.v3.Value.string:type_name -> google.protobuf.StringValue
	8,  // 1: cedar.v3.Value.long:type_name -> google.protobuf.Int64Value
	9,  // 2: cedar.v3.Value.bool:type_name -> google.protobuf.BoolValue
	1,  // 3: cedar.v3.Value.set:type_name -> cedar.v3.SetValue
	2,  // 4: cedar.v3.Value.record:type_name -> cedar.v3.RecordValue
	3,  // 5: cedar.v3.Value.extension_call:type_name -> cedar.v3.ExtensionCall
	4,  // 6: cedar.v3.Value.entity:type_name -> cedar.v3.EntityValue
	5,  // 7: cedar.v3.Value.decimal:type_name -> cedar.v3.DecimalValue
	0,  // 8: cedar.v3.SetValue.elements:type_name -> cedar.v3.Value
	6,  // 9: cedar.v3.RecordValue.attributes:type_name -> cedar.v3.RecordValue.AttributesEntry
	0,  // 10: cedar.v3.ExtensionCall.arg:type_name -> cedar.v3.Value
	10, // 11: cedar.v3.EntityValue.uid:type_name -> cedar.v3.EntityUid
	0,  // 12: cedar.v3.RecordValue.AttributesEntry.value:type_name -> cedar.v3.Value
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_cedar_v3_value_proto_init() }
func file_cedar_v3_value_proto_init() {
	if File_cedar_v3_value_proto != nil {
		return
	}
	file_cedar_v3_entity_uid_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cedar_v3_value_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cedar_v3_value_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SetValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cedar_v3_value_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RecordValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cedar_v3_value_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ExtensionCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cedar_v3_value_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*EntityValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cedar_v3_value_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DecimalValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cedar_v3_value_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_String_)(nil),
		(*Value_Long)(nil),
		(*Value_Bool)(nil),
		(*Value_Set)(nil),
		(*Value_Record)(nil),
		(*Value_ExtensionCall)(nil),
		(*Value_Entity)(nil),
		(*Value_Decimal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cedar_v3_value_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cedar_v3_value_proto_goTypes,
		DependencyIndexes: file_cedar_v3_value_proto_depIdxs,
		MessageInfos:      file_cedar_v3_value_proto_msgTypes,
	}.Build()
	File_cedar_v3_value_proto = out.File
	file_cedar_v3_value_proto_rawDesc = nil
	file_cedar_v3_value_proto_goTypes = nil
	file_cedar_v3_value_proto_depIdxs = nil
}
