// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: cedar/v3/value.proto

package cedarv3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*Value_String_
	//	*Value_Long
	//	*Value_Bool
	//	*Value_Set
	//	*Value_Record
	//	*Value_Extension
	//	*Value_Entity
	Value isValue_Value `protobuf_oneof:"value"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cedar_v3_value_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v3_value_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_cedar_v3_value_proto_rawDescGZIP(), []int{0}
}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Value) GetString_() string {
	if x, ok := x.GetValue().(*Value_String_); ok {
		return x.String_
	}
	return ""
}

func (x *Value) GetLong() int64 {
	if x, ok := x.GetValue().(*Value_Long); ok {
		return x.Long
	}
	return 0
}

func (x *Value) GetBool() bool {
	if x, ok := x.GetValue().(*Value_Bool); ok {
		return x.Bool
	}
	return false
}

func (x *Value) GetSet() *SetValue {
	if x, ok := x.GetValue().(*Value_Set); ok {
		return x.Set
	}
	return nil
}

func (x *Value) GetRecord() *RecordValue {
	if x, ok := x.GetValue().(*Value_Record); ok {
		return x.Record
	}
	return nil
}

func (x *Value) GetExtension() *ExtensionValue {
	if x, ok := x.GetValue().(*Value_Extension); ok {
		return x.Extension
	}
	return nil
}

func (x *Value) GetEntity() *EntityValue {
	if x, ok := x.GetValue().(*Value_Entity); ok {
		return x.Entity
	}
	return nil
}

type isValue_Value interface {
	isValue_Value()
}

type Value_String_ struct {
	String_ string `protobuf:"bytes,1,opt,name=string,proto3,oneof"`
}

type Value_Long struct {
	Long int64 `protobuf:"varint,2,opt,name=long,proto3,oneof"`
}

type Value_Bool struct {
	Bool bool `protobuf:"varint,3,opt,name=bool,proto3,oneof"`
}

type Value_Set struct {
	Set *SetValue `protobuf:"bytes,4,opt,name=set,proto3,oneof"`
}

type Value_Record struct {
	Record *RecordValue `protobuf:"bytes,5,opt,name=record,proto3,oneof"`
}

type Value_Extension struct {
	Extension *ExtensionValue `protobuf:"bytes,6,opt,name=extension,proto3,oneof"`
}

type Value_Entity struct {
	Entity *EntityValue `protobuf:"bytes,7,opt,name=entity,proto3,oneof"`
}

func (*Value_String_) isValue_Value() {}

func (*Value_Long) isValue_Value() {}

func (*Value_Bool) isValue_Value() {}

func (*Value_Set) isValue_Value() {}

func (*Value_Record) isValue_Value() {}

func (*Value_Extension) isValue_Value() {}

func (*Value_Entity) isValue_Value() {}

type SetValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *SetValue) Reset() {
	*x = SetValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cedar_v3_value_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValue) ProtoMessage() {}

func (x *SetValue) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v3_value_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValue.ProtoReflect.Descriptor instead.
func (*SetValue) Descriptor() ([]byte, []int) {
	return file_cedar_v3_value_proto_rawDescGZIP(), []int{1}
}

func (x *SetValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type RecordValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values map[string]*Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *RecordValue) Reset() {
	*x = RecordValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cedar_v3_value_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordValue) ProtoMessage() {}

func (x *RecordValue) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v3_value_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordValue.ProtoReflect.Descriptor instead.
func (*RecordValue) Descriptor() ([]byte, []int) {
	return file_cedar_v3_value_proto_rawDescGZIP(), []int{2}
}

func (x *RecordValue) GetValues() map[string]*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type ExtensionValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fn  string `protobuf:"bytes,1,opt,name=fn,proto3" json:"fn,omitempty"`
	Arg *Value `protobuf:"bytes,2,opt,name=arg,proto3" json:"arg,omitempty"`
}

func (x *ExtensionValue) Reset() {
	*x = ExtensionValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cedar_v3_value_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtensionValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionValue) ProtoMessage() {}

func (x *ExtensionValue) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v3_value_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionValue.ProtoReflect.Descriptor instead.
func (*ExtensionValue) Descriptor() ([]byte, []int) {
	return file_cedar_v3_value_proto_rawDescGZIP(), []int{3}
}

func (x *ExtensionValue) GetFn() string {
	if x != nil {
		return x.Fn
	}
	return ""
}

func (x *ExtensionValue) GetArg() *Value {
	if x != nil {
		return x.Arg
	}
	return nil
}

type EntityValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid *EntityId `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *EntityValue) Reset() {
	*x = EntityValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cedar_v3_value_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityValue) ProtoMessage() {}

func (x *EntityValue) ProtoReflect() protoreflect.Message {
	mi := &file_cedar_v3_value_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityValue.ProtoReflect.Descriptor instead.
func (*EntityValue) Descriptor() ([]byte, []int) {
	return file_cedar_v3_value_proto_rawDescGZIP(), []int{4}
}

func (x *EntityValue) GetUid() *EntityId {
	if x != nil {
		return x.Uid
	}
	return nil
}

var File_cedar_v3_value_proto protoreflect.FileDescriptor

var file_cedar_v3_value_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2f, 0x76, 0x33, 0x2f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2e, 0x76, 0x33,
	0x1a, 0x18, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2f, 0x76, 0x33, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9a, 0x02, 0x0a, 0x05, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14,
	0x0a, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x04,
	0x6c, 0x6f, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6c, 0x12, 0x26, 0x0a, 0x03, 0x73, 0x65,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2e,
	0x76, 0x33, 0x2e, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x03, 0x73,
	0x65, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2e, 0x76, 0x33, 0x2e, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2e, 0x76,
	0x33, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x48, 0x00, 0x52, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a,
	0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x63, 0x65, 0x64, 0x61, 0x72, 0x2e, 0x76, 0x33, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x07,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x33, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2e, 0x76, 0x33, 0x2e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x94, 0x01, 0x0a,
	0x0b, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x39, 0x0a, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63,
	0x65, 0x64, 0x61, 0x72, 0x2e, 0x76, 0x33, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x4a, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2e,
	0x76, 0x33, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x43, 0x0a, 0x0e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x66, 0x6e, 0x12, 0x21, 0x0a, 0x03, 0x61, 0x72, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2e, 0x76, 0x33, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x03, 0x61, 0x72, 0x67, 0x22, 0x33, 0x0a, 0x0b, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x24, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2e, 0x76, 0x33, 0x2e,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x52, 0x03, 0x75, 0x69, 0x64, 0x42, 0x92, 0x01,
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2e, 0x76, 0x33, 0x42, 0x0a,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x35, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x65, 0x6c, 0x65, 0x73, 0x74, 0x2d,
	0x64, 0x65, 0x76, 0x2f, 0x63, 0x6f, 0x72, 0x6b, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x63, 0x65, 0x64, 0x61, 0x72, 0x2f, 0x76, 0x33, 0x3b, 0x63, 0x65, 0x64, 0x61,
	0x72, 0x76, 0x33, 0xa2, 0x02, 0x03, 0x43, 0x58, 0x58, 0xaa, 0x02, 0x08, 0x43, 0x65, 0x64, 0x61,
	0x72, 0x2e, 0x56, 0x33, 0xca, 0x02, 0x08, 0x43, 0x65, 0x64, 0x61, 0x72, 0x5c, 0x56, 0x33, 0xe2,
	0x02, 0x14, 0x43, 0x65, 0x64, 0x61, 0x72, 0x5c, 0x56, 0x33, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x43, 0x65, 0x64, 0x61, 0x72, 0x3a, 0x3a,
	0x56, 0x33, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cedar_v3_value_proto_rawDescOnce sync.Once
	file_cedar_v3_value_proto_rawDescData = file_cedar_v3_value_proto_rawDesc
)

func file_cedar_v3_value_proto_rawDescGZIP() []byte {
	file_cedar_v3_value_proto_rawDescOnce.Do(func() {
		file_cedar_v3_value_proto_rawDescData = protoimpl.X.CompressGZIP(file_cedar_v3_value_proto_rawDescData)
	})
	return file_cedar_v3_value_proto_rawDescData
}

var file_cedar_v3_value_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cedar_v3_value_proto_goTypes = []any{
	(*Value)(nil),          // 0: cedar.v3.Value
	(*SetValue)(nil),       // 1: cedar.v3.SetValue
	(*RecordValue)(nil),    // 2: cedar.v3.RecordValue
	(*ExtensionValue)(nil), // 3: cedar.v3.ExtensionValue
	(*EntityValue)(nil),    // 4: cedar.v3.EntityValue
	nil,                    // 5: cedar.v3.RecordValue.ValuesEntry
	(*EntityId)(nil),       // 6: cedar.v3.EntityId
}
var file_cedar_v3_value_proto_depIdxs = []int32{
	1, // 0: cedar.v3.Value.set:type_name -> cedar.v3.SetValue
	2, // 1: cedar.v3.Value.record:type_name -> cedar.v3.RecordValue
	3, // 2: cedar.v3.Value.extension:type_name -> cedar.v3.ExtensionValue
	4, // 3: cedar.v3.Value.entity:type_name -> cedar.v3.EntityValue
	0, // 4: cedar.v3.SetValue.values:type_name -> cedar.v3.Value
	5, // 5: cedar.v3.RecordValue.values:type_name -> cedar.v3.RecordValue.ValuesEntry
	0, // 6: cedar.v3.ExtensionValue.arg:type_name -> cedar.v3.Value
	6, // 7: cedar.v3.EntityValue.uid:type_name -> cedar.v3.EntityId
	0, // 8: cedar.v3.RecordValue.ValuesEntry.value:type_name -> cedar.v3.Value
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_cedar_v3_value_proto_init() }
func file_cedar_v3_value_proto_init() {
	if File_cedar_v3_value_proto != nil {
		return
	}
	file_cedar_v3_entity_id_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cedar_v3_value_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cedar_v3_value_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SetValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cedar_v3_value_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RecordValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cedar_v3_value_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ExtensionValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cedar_v3_value_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*EntityValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cedar_v3_value_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_String_)(nil),
		(*Value_Long)(nil),
		(*Value_Bool)(nil),
		(*Value_Set)(nil),
		(*Value_Record)(nil),
		(*Value_Extension)(nil),
		(*Value_Entity)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cedar_v3_value_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cedar_v3_value_proto_goTypes,
		DependencyIndexes: file_cedar_v3_value_proto_depIdxs,
		MessageInfos:      file_cedar_v3_value_proto_msgTypes,
	}.Build()
	File_cedar_v3_value_proto = out.File
	file_cedar_v3_value_proto_rawDesc = nil
	file_cedar_v3_value_proto_goTypes = nil
	file_cedar_v3_value_proto_depIdxs = nil
}
